import { useEffect, useRef, useState } from 'react';
import { useAuth } from '../../hooks/useAuth';
import { useTenantSchool } from '../../hooks/useTenantSchool';
import { fetchApi } from '../../lib/api';
import {PROGRESS_PERIODS,type ProgressPeriod,type GradeProgressReport,type GradeProgressSnapshot} from '../../lib/gradeProgress';
const input='min-w-0 w-full rounded-lg border bg-white p-2.5';
const button='rounded-lg bg-primary-600 px-4 py-2 text-white disabled:opacity-50';
export default function GradeProgressPage(){
 const {user}=useAuth(),{schoolId,isSystemAdmin,schools,selectSchool}=useTenantSchool(),parent=user?.role_key==='parent';
 const [reports,setReports]=useState<GradeProgressReport[]>([]),[students,setStudents]=useState<Array<{id:number;full_name:string}>>([]);
 const [student,setStudent]=useState(''),[period,setPeriod]=useState<ProgressPeriod>('first_month');
 const [preview,setPreview]=useState<{snapshot:GradeProgressSnapshot;preview_digest:string}|null>(null),[delivered,setDelivered]=useState(false);
 const [error,setError]=useState(''),[busy,setBusy]=useState(false),[reason,setReason]=useState(''),[selected,setSelected]=useState<string|null>(null),[cursor,setCursor]=useState<number|null>(null);
 const epoch=useRef(0),key=useRef('');
 async function load(before?:number){if(!schoolId)return;const token=epoch.current;const r=await fetchApi<{reports:GradeProgressReport[];next_cursor:number|null}>(`/api/grade-progress?school_id=${schoolId}${before?`&before=${before}`:''}`);if(token!==epoch.current)return;if(r.error)setError(r.error);else if(r.data){setError('');setReports(old=>before?[...old,...r.data!.reports]:r.data!.reports);setCursor(r.data.next_cursor);}}
 useEffect(()=>{epoch.current++;setReports([]);setStudents([]);setStudent('');setPreview(null);setDelivered(false);setSelected(null);setError('');setBusy(false);setReason('');key.current='';void load();const token=epoch.current;
 if(schoolId&&!parent)fetchApi<Array<{id:number;full_name:string}>>(`/api/students?school_id=${schoolId}`).then(r=>{if(token===epoch.current){if(r.error)setError(r.error);else setStudents(r.data||[]);}});
 return()=>{epoch.current++;};},[schoolId,parent]);
 function reset(){setPreview(null);setDelivered(false);key.current='';}
 async function makePreview(){if(!schoolId||!student||busy)return;const token=epoch.current;setBusy(true);setError('');reset();const r=await fetchApi<{snapshot:GradeProgressSnapshot;preview_digest:string}>('/api/grade-progress/preview',{method:'POST',body:JSON.stringify({school_id:schoolId,student_id:Number(student),period})});if(token!==epoch.current)return;setBusy(false);if(r.error)setError(r.error);else setPreview(r.data||null);}
 async function publish(){if(!preview||!delivered||busy)return;const token=epoch.current;setBusy(true);setError('');key.current ||= crypto.randomUUID();const r=await fetchApi<GradeProgressReport>('/api/grade-progress/publish',{method:'POST',body:JSON.stringify({school_id:schoolId,student_id:Number(student),period,report_key:key.current,preview_digest:preview.preview_digest,confirm_delivered:delivered})});if(token!==epoch.current)return;setBusy(false);if(r.error)setError(r.error);else{reset();await load();setSelected(r.data?.report_key||null);}}
 async function withdraw(r:GradeProgressReport){if(!reason.trim()||busy)return;const token=epoch.current;setBusy(true);setError('');const result=await fetchApi(`/api/grade-progress/${r.report_key}/withdraw`,{method:'POST',body:JSON.stringify({school_id:schoolId,revision:r.revision,reason})});if(token!==epoch.current)return;setBusy(false);if(result.error)setError(result.error);else{setReason('');await load();}}
 const report=reports.find(r=>r.report_key===selected);
 const render=(s:GradeProgressSnapshot)=><div className="space-y-3"><h2 className="text-lg font-bold">متابعة {s.period_label}</h2><p>{s.student_name} — {s.student_number}</p><p className="text-sm text-gray-500">{s.year_name} · {s.class_name} {s.section_name&&`/ ${s.section_name}`}</p><p className="text-sm text-gray-600">متابعة للفترة الدراسية؛ النتيجة السنوية الرسمية متاحة في كارت النتائج.</p><table className="w-full border-collapse text-sm"><thead><tr><th className="border p-2 text-right">المادة</th><th className="border p-2">الدرجة / {s.max_grade}</th></tr></thead><tbody>{s.subjects.map((v,i)=><tr key={i}><td className="break-words border p-2">{v.subject_name}</td><td className="border p-2 text-center">{v.score==null?'لم تُدخل':v.score}</td></tr>)}</tbody></table>{s.missing_count>0&&<p className="text-sm text-amber-700">درجات غير مدخلة: {s.missing_count}</p>}</div>;
 return <div className="space-y-5 p-4 sm:p-6" dir="rtl"><style>{`@media print{@page{size:A4;margin:12mm}body:has(.grade-progress-print) *{visibility:hidden}body .grade-progress-print,body .grade-progress-print *{visibility:visible}.grade-progress-print{position:absolute;inset:0;width:100%;border:0!important;box-shadow:none!important}.grade-progress-print tr{break-inside:avoid}}`}</style>
 <div className="flex flex-wrap items-center justify-between gap-3"><h1 className="text-2xl font-bold">متابعة الدرجات</h1><button className="text-primary-700" onClick={()=>void load()}>تحديث</button></div>
 {isSystemAdmin&&<label className="block">المدرسة<select className={input} value={schoolId||''} onChange={e=>selectSchool(e.target.value?Number(e.target.value):null)}><option value="">اختر المدرسة</option>{schools.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label>}
 {error&&<p role="alert" className="rounded-lg bg-red-50 p-3 text-red-700">{error}</p>}
 {!parent&&<section className="space-y-4 rounded-xl border bg-white p-4"><h2 className="font-bold">إعداد متابعة ونشرها</h2><div className="grid gap-3 sm:grid-cols-2"><label>الطالب<select className={input} disabled={busy} value={student} onChange={e=>{setStudent(e.target.value);reset();}}><option value="">اختر الطالب</option>{students.map(s=><option key={s.id} value={s.id}>{s.full_name}</option>)}</select></label><label>الفترة<select className={input} disabled={busy} value={period} onChange={e=>{setPeriod(e.target.value as ProgressPeriod);reset();}}>{Object.entries(PROGRESS_PERIODS).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label></div><button className={button} disabled={busy||!student} onClick={()=>void makePreview()}>معاينة الدرجات</button>
 {preview&&<div className="space-y-4 border-t pt-4">{render(preview.snapshot)}<label className="flex gap-2"><input type="checkbox" checked={delivered} onChange={e=>setDelivered(e.target.checked)} />أكدت تسليم هذه المتابعة للطالب</label><button className={button} disabled={busy||!delivered} onClick={()=>void publish()}>نشر لولي الأمر المرتبط</button></div>}</section>}
 <div className="grid min-w-0 gap-4 lg:grid-cols-2"><section className="space-y-2"><h2 className="font-bold">المتابعات المنشورة</h2>{reports.length===0&&<p className="p-5 text-gray-500">لا توجد متابعات منشورة متاحة.</p>}{reports.map(r=><button key={r.report_key} disabled={busy} className={`w-full rounded-lg border p-3 text-right ${selected===r.report_key?'border-primary-500 bg-primary-50':'bg-white'}`} onClick={()=>{setSelected(r.report_key);setReason('');}}><b className="block">{r.snapshot.student_name} — {r.snapshot.period_label}</b><span className="text-xs">{r.status==='published'?'منشورة':'مسحوبة'} · {new Date(r.created_at*1000).toLocaleString('ar-IQ')}</span></button>)}{cursor&&<button className={button} onClick={()=>void load(cursor)}>المزيد</button>}</section>
 {report&&<section className="min-w-0 space-y-4"><div className={report.status==='published'?'grade-progress-print rounded-xl border bg-white p-5':'rounded-xl border bg-white p-5'}>{render(report.snapshot)}{report.status==='withdrawn'&&<p className="mt-4 text-red-700">سُحبت هذه المتابعة.</p>}</div>{report.status==='published'&&<button className={button} onClick={()=>window.print()}>طباعة A4</button>}{!parent&&report.status==='published'&&<div className="space-y-2"><label className="block">سبب سحب المتابعة<input className={input} value={reason} maxLength={500} onChange={e=>setReason(e.target.value)} /></label><button className="rounded-lg border border-red-300 px-4 py-2 text-red-700 disabled:opacity-50" disabled={busy||!reason.trim()} onClick={()=>void withdraw(report)}>سحب المتابعة</button><p className="text-xs text-gray-500">للتصحيح: اسحب المتابعة ثم انشر نسخة جديدة بعد مراجعة الدرجات.</p></div>}</section>}</div>
 </div>;
}
