import {useEffect,useState} from 'react';
import {useNavigate} from 'react-router-dom';
import {AlertTriangle,CheckCircle2,Download,FileText,Receipt,Users,Wallet} from 'lucide-react';
import {getParentStudentFinance} from '../../lib/api';
import {formatFinanceDate,formatIqd,formatPercentageBasisPoints,installmentStatusClasses,installmentStatusLabel,paymentMethodLabel} from '../../lib/financePresentation';

export default function ParentFinanceSection({studentId}:{studentId:number}){
  const navigate=useNavigate(),[data,setData]=useState<any>(null),[loading,setLoading]=useState(true),[error,setError]=useState('');
  useEffect(()=>{let active=true;setLoading(true);setError('');setData(null);void getParentStudentFinance(studentId).then(response=>{if(!active)return;if(response.error)setError(response.error);else setData(response.data);setLoading(false);});return()=>{active=false;};},[studentId]);
  if(loading)return <section className="rounded-xl border border-gray-200 bg-white p-6" aria-label="الأقساط"><p className="text-center text-sm text-gray-500">جاري تحميل الأقساط...</p></section>;
  if(error)return <section className="rounded-xl border border-red-200 bg-red-50 p-5" aria-label="الأقساط"><div className="flex items-center gap-2 text-red-700"><AlertTriangle size={19}/><span>{error}</span></div></section>;
  const totals=data?.totals??{},ratio=Math.min(100,Math.max(0,Number(totals.payment_ratio_basis_points||0)/100));
  return <section className="overflow-hidden rounded-xl border border-emerald-200 bg-white" aria-label="الأقساط">
    <div className="flex flex-wrap items-center justify-between gap-3 border-b border-emerald-100 bg-emerald-50 px-6 py-4"><div className="flex items-center gap-3"><div className="rounded-xl bg-emerald-100 p-2 text-emerald-700"><Wallet size={22}/></div><div><h2 className="text-lg font-bold text-gray-900">الأقساط</h2><p className="text-xs text-gray-600">عرض فقط — المبالغ المحسوبة من سجلات المدرسة</p></div></div>{data?.linked_students?.length>1&&<label className="flex items-center gap-2 text-sm text-gray-700"><Users size={17}/><span>اختيار الابن</span><select value={studentId} onChange={event=>navigate(`/students/${event.target.value}`)} className="rounded-lg border border-emerald-200 bg-white px-3 py-2">{data.linked_students.map((student:any)=><option key={student.id} value={student.id}>{student.full_name}</option>)}</select></label>}</div>
    <div className="space-y-6 p-5 sm:p-6">
      <div className="grid grid-cols-2 gap-3 lg:grid-cols-5">{[['الرسوم الأصلية',totals.original_fee],['الخصومات',totals.discount_amount],['الصافي',totals.net_due],['المدفوع',totals.paid_amount],['المتبقي',totals.remaining_amount]].map(([label,value])=><div key={String(label)} className="rounded-xl bg-gray-50 p-3"><p className="text-xs text-gray-500">{label}</p><p className="mt-1 font-bold text-gray-900">{formatIqd(Number(value||0))}</p></div>)}</div>
      <div><div className="mb-2 flex justify-between text-sm"><span className="font-semibold text-gray-700">نسبة التسديد</span><span className="font-bold text-emerald-700">{ratio.toLocaleString('ar-IQ',{maximumFractionDigits:2})}%</span></div><div className="h-3 overflow-hidden rounded-full bg-gray-100"><div className="h-full rounded-full bg-emerald-500 transition-all" style={{width:`${ratio}%`}}/></div></div>
      {!data?.fees?.length?<div className="rounded-xl bg-gray-50 p-8 text-center"><CheckCircle2 className="mx-auto mb-2 text-gray-300"/><p className="text-sm text-gray-600">لا توجد أقساط مسجلة لهذا الطالب.</p></div>:<div className="space-y-4">{data.fees.map((fee:any)=><article key={fee.id} className="rounded-xl border border-gray-200"><div className="grid gap-3 p-4 sm:grid-cols-[1fr_auto]"><div><h3 className="font-bold text-gray-900">{fee.fee_type}</h3><p className="mt-1 text-xs text-gray-500">{fee.academic_year_name||'سنة دراسية غير محددة'} · الاستحقاق {formatFinanceDate(fee.due_date)}</p></div><div className="text-left"><p className="font-bold text-gray-900">{formatIqd(fee.net_fee??fee.amount)}</p><p className="text-xs text-gray-500">متبقي {formatIqd(fee.remaining_amount)}</p></div></div>{fee.installment_plan&&<div className="border-t border-gray-100 p-4"><h4 className="mb-2 text-sm font-bold text-gray-800">جدول الدفعات</h4><div className="overflow-x-auto"><table className="w-full min-w-[620px] text-sm"><thead className="bg-gray-50 text-gray-600"><tr><th className="p-2 text-right">الدفعة</th><th className="p-2 text-right">النسبة</th><th className="p-2 text-right">المبلغ</th><th className="p-2 text-right">التاريخ</th><th className="p-2 text-right">المدفوع</th><th className="p-2 text-right">الحالة</th></tr></thead><tbody className="divide-y divide-gray-100">{fee.installment_plan.items.map((item:any)=><tr key={item.id}><td className="p-2 font-medium">{item.label}</td><td className="p-2">{formatPercentageBasisPoints(item.percentage_basis_points)}</td><td className="p-2">{formatIqd(item.amount)}</td><td className="p-2">{formatFinanceDate(item.due_date)}</td><td className="p-2">{formatIqd(item.paid_amount)}</td><td className="p-2"><span className={`rounded-full px-2 py-1 text-xs font-semibold ${installmentStatusClasses(item.status)}`}>{installmentStatusLabel(item.status)}</span></td></tr>)}</tbody></table></div></div>}</article>)}</div>}
      <div className="grid gap-5 lg:grid-cols-2"><div className="overflow-hidden rounded-xl border border-gray-200"><div className="flex items-center gap-2 border-b bg-gray-50 px-4 py-3"><Receipt size={18}/><h3 className="font-bold">سجل الدفعات</h3></div><div className="divide-y divide-gray-100">{!data?.payments?.length?<p className="p-5 text-center text-sm text-gray-500">لا توجد دفعات.</p>:data.payments.map((payment:any)=><div key={payment.id} className={`flex items-center justify-between gap-3 p-4 ${payment.status==='cancelled'?'bg-gray-50 text-gray-500':''}`}><div><p className="font-semibold">{payment.fee_type}</p><p className="text-xs">{paymentMethodLabel(payment.payment_method)} · {formatFinanceDate(payment.payment_date)}</p></div><div className="text-left"><p className="font-bold">{formatIqd(payment.amount)}</p><span className={`text-xs ${payment.status==='cancelled'?'text-red-600':'text-emerald-700'}`}>{payment.status==='cancelled'?'ملغاة':'فعالة'}</span></div></div>)}</div></div>
        <div className="overflow-hidden rounded-xl border border-gray-200"><div className="flex items-center gap-2 border-b bg-gray-50 px-4 py-3"><FileText size={18}/><h3 className="font-bold">الإيصالات</h3></div><div className="divide-y divide-gray-100">{!data?.receipts?.length?<p className="p-5 text-center text-sm text-gray-500">لا توجد إيصالات.</p>:data.receipts.map((receipt:any)=><div key={receipt.id} className={`flex items-center justify-between gap-3 p-4 ${receipt.status==='cancelled'?'bg-red-50/50':''}`}><div><p className="font-mono text-sm font-semibold" dir="ltr">{receipt.receipt_number}</p><p className="text-xs text-gray-500">{formatFinanceDate(receipt.created_at)} · {formatIqd(receipt.total_amount)}</p>{receipt.replaces_receipt_id&&<p className="mt-1 text-xs text-blue-700">إيصال بديل عن مستند ملغى</p>}</div><div className="flex items-center gap-2"><span className={`rounded-full px-2 py-1 text-xs font-semibold ${receipt.status==='active'?'bg-emerald-100 text-emerald-700':'bg-red-100 text-red-700'}`}>{receipt.status==='active'?'فعال':'ملغى'}</span><a href={`/print/receipt/${receipt.id}`} className="rounded-lg p-2 text-primary-700 hover:bg-primary-50" title="عرض أو حفظ PDF"><Download size={17}/></a><a href={`/verify/receipt/${receipt.verification_token}`} target="_blank" rel="noreferrer" className="rounded-lg p-2 text-gray-600 hover:bg-gray-100" title="التحقق من QR"><Receipt size={17}/></a></div></div>)}</div></div></div>
    </div>
  </section>;
}
