import {useEffect,useRef,useState} from 'react';
import {useTenantSchool} from '../../hooks/useTenantSchool';
import {useAuth} from '../../hooks/useAuth';
import {fetchApi} from '../../lib/api';
import {hasRole,SCHOOL_MANAGEMENT_ROLES} from '../../lib/rbac';
import {ADMISSION_PROCESSES} from '../../lib/admissionRegulations';
import type {AdmissionApplication,AdmissionPreview} from '../../lib/admissions';
import {useSchoolOptions,workflowInput as input,workflowButton as button} from './useSchoolOptions';
const labels={submitted:'قيد المراجعة',approved:'معتمد',rejected:'مرفوض',cancelled:'ملغى',executed:'منفذ'};
const empty=()=>({student_id:'',full_name:'',student_number:'',gender:'male',birth_date:'',academic_year_id:'',class_id:'',section_id:'',process:'admission',external_school:'',document_reference:'',previous_repeats:'',accelerated:'',documents:''});
const facts=(f:{previous_repeats:string;accelerated:string;documents:string})=>({previous_repeats:f.previous_repeats.trim()===''?null:Number(f.previous_repeats),accelerated:f.accelerated===''?null:f.accelerated==='yes',documents:f.documents.split('\n').map(x=>x.trim()).filter(Boolean)});
export default function AdmissionsPage(){
 const scope=useTenantSchool(),{schoolId}=scope,{user}=useAuth(),options=useSchoolOptions(schoolId),canDecide=hasRole(user?.role_key,SCHOOL_MANAGEMENT_ROLES);
 const [rows,setRows]=useState<AdmissionApplication[]>([]),[form,setForm]=useState(empty),[selected,setSelected]=useState<AdmissionApplication|null>(null),[preview,setPreview]=useState<AdmissionPreview|null>(null),[reason,setReason]=useState(''),[verified,setVerified]=useState(false),[confirm,setConfirm]=useState(false),[error,setError]=useState(''),[busy,setBusy]=useState(false),[cursor,setCursor]=useState<number|null>(null),[audit,setAudit]=useState<Array<{new_status:string;reason:string|null;created_at:number}>>([]),[edit,setEdit]=useState({previous_repeats:'',accelerated:'',documents:''});
 const epoch=useRef(0),selectionEpoch=useRef(0),key=useRef('');
 async function load(before?:number){if(!schoolId)return;const token=epoch.current;const r=await fetchApi<{applications:AdmissionApplication[];next_cursor:number|null}>(`/api/admissions?school_id=${schoolId}${before?`&before=${before}`:''}`);if(token!==epoch.current)return;if(r.error)setError(r.error);else if(r.data){setRows(old=>before?[...old,...r.data!.applications]:r.data!.applications);setCursor(r.data.next_cursor);}}
 useEffect(()=>{epoch.current++;selectionEpoch.current++;setRows([]);setForm(empty());setSelected(null);setPreview(null);setAudit([]);setError('');setBusy(false);setReason('');setVerified(false);setConfirm(false);setCursor(null);key.current='';void load();return()=>{epoch.current++;selectionEpoch.current++;};},[schoolId]);
 function change(k:keyof ReturnType<typeof empty>,v:string){setForm(f=>({...f,[k]:v,...(k==='class_id'?{section_id:''}:{})}));key.current='';}
 async function choose(a:AdmissionApplication){const token=epoch.current,seq=++selectionEpoch.current;setSelected(a);setPreview(null);setAudit([]);setReason('');setVerified(false);setConfirm(false);setEdit({previous_repeats:a.facts.previous_repeats==null?'':String(a.facts.previous_repeats),accelerated:a.facts.accelerated==null?'':a.facts.accelerated?'yes':'no',documents:a.facts.documents.join('\n')});
 const responses=await Promise.all([a.status==='submitted'||a.status==='approved'?fetchApi<AdmissionPreview>(`/api/admissions/${a.application_key}/preview?school_id=${schoolId}`):Promise.resolve({data:undefined,error:undefined}),fetchApi<Array<{new_status:string;reason:string|null;created_at:number}>>(`/api/admissions/${a.application_key}/audit?school_id=${schoolId}`)]);
 if(token!==epoch.current||seq!==selectionEpoch.current)return;if(responses[0].error)setError(responses[0].error);else setPreview(responses[0].data||null);if(responses[1].error)setError(responses[1].error);else setAudit(responses[1].data||[]);}
 async function create(e:React.FormEvent){e.preventDefault();if(!schoolId||busy)return;const token=epoch.current;setBusy(true);setError('');key.current ||= crypto.randomUUID();const r=await fetchApi<AdmissionApplication>('/api/admissions',{method:'POST',body:JSON.stringify({school_id:schoolId,application_key:key.current,student_id:form.student_id?Number(form.student_id):null,applicant:form.student_id?null:{full_name:form.full_name,student_number:form.student_number,gender:form.gender,birth_date:form.birth_date||null},academic_year_id:Number(form.academic_year_id),class_id:Number(form.class_id),section_id:form.section_id?Number(form.section_id):null,process:form.process,external_school:form.external_school,document_reference:form.document_reference,facts:facts(form)})});if(token!==epoch.current)return;setBusy(false);if(r.error)setError(r.error);else{key.current='';setForm(empty());await load();if(r.data)await choose(r.data);}}
 async function action(kind:string){if(!selected||!schoolId||busy)return;const token=epoch.current;setBusy(true);setError('');const suffix=kind==='execute'?'execute':kind==='facts'?'facts':'decision',body=kind==='execute'?{confirm_execute:confirm}:kind==='facts'?{facts:facts(edit),reason}:{decision:kind,reason,preview_digest:preview?.preview_digest,confirm_evidence_verified:verified};
 const r=await fetchApi<AdmissionApplication>(`/api/admissions/${selected.application_key}/${suffix}`,{method:kind==='facts'?'PUT':'POST',body:JSON.stringify({school_id:schoolId,revision:selected.revision,...body})});if(token!==epoch.current)return;setBusy(false);if(r.error)setError(r.error);else{await load();if(r.data)await choose(r.data);}}
 const evidenceFields=(f:{previous_repeats:string;accelerated:string;documents:string},onChange:(k:'previous_repeats'|'accelerated'|'documents',v:string)=>void)=><div className="space-y-3"><div className="grid gap-3 sm:grid-cols-2"><label>سنوات الإعادة السابقة<input className={input} type="number" min={0} max={30} value={f.previous_repeats} onChange={e=>onChange('previous_repeats',e.target.value)} placeholder="غير مثبت" /></label><label>هل الطلب يتضمن تسريعًا؟<select className={input} value={f.accelerated} onChange={e=>onChange('accelerated',e.target.value)}><option value="">غير مثبت</option><option value="no">لا</option><option value="yes">نعم</option></select></label></div><label className="block">المستندات التي فُحصت — سطر لكل نوع<textarea className={input} rows={3} value={f.documents} onChange={e=>onChange('documents',e.target.value)} /></label></div>;
 return <div dir="rtl" className="space-y-5 p-4 sm:p-6"><div className="flex flex-wrap justify-between gap-3"><h1 className="text-2xl font-bold">القبول والنقل</h1><button className="text-primary-700" onClick={()=>void load()}>تحديث الطلبات</button></div><p className="text-sm text-gray-600">تُراجع الشروط والمستندات، ثم تعتمد الإدارة الطلب قبل تنفيذ التسجيل أو النقل.</p>
 {scope.isSystemAdmin&&<label>المدرسة<select className={input} value={schoolId||''} onChange={e=>scope.selectSchool(e.target.value?Number(e.target.value):null)}><option value="">اختر المدرسة</option>{scope.schools.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label>}
 {(error||options.error)&&<p role="alert" className="rounded-lg bg-red-50 p-3 text-red-700">{error||options.error}</p>}
 <details className="rounded-xl border bg-white p-4"><summary className="cursor-pointer font-bold">طلب جديد</summary><form onSubmit={create} className="mt-4 space-y-4"><fieldset disabled={busy} className="space-y-4"><div className="grid gap-3 sm:grid-cols-2"><label>نوع الطلب<select className={input} value={form.process} onChange={e=>change('process',e.target.value)}>{Object.entries(ADMISSION_PROCESSES).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label><label>ملف الطالب<select className={input} value={form.student_id} required={form.process==='transfer_out'} onChange={e=>change('student_id',e.target.value)}><option value="">متقدم جديد</option>{options.students.map(s=><option key={s.id} value={s.id}>{s.full_name}</option>)}</select></label></div>
 {!form.student_id&&<div className="grid gap-3 sm:grid-cols-2"><label>اسم الطالب<input className={input} required maxLength={200} value={form.full_name} onChange={e=>change('full_name',e.target.value)} /></label><label>رقم الطالب<input className={input} required maxLength={50} value={form.student_number} onChange={e=>change('student_number',e.target.value)} /></label><label>الجنس<select className={input} value={form.gender} onChange={e=>change('gender',e.target.value)}><option value="male">ذكر</option><option value="female">أنثى</option></select></label><label>تاريخ الميلاد<input className={input} type="date" value={form.birth_date} onChange={e=>change('birth_date',e.target.value)} /></label></div>}
 <div className="grid gap-3 sm:grid-cols-3"><label>السنة<select className={input} required value={form.academic_year_id} onChange={e=>change('academic_year_id',e.target.value)}><option value="">اختر السنة</option>{options.years.map(y=><option key={y.id} value={y.id}>{y.name}</option>)}</select></label><label>الصف<select className={input} required value={form.class_id} onChange={e=>change('class_id',e.target.value)}><option value="">اختر الصف</option>{options.classes.filter(c=>c.status==='active').map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label>الشعبة<select className={input} value={form.section_id} onChange={e=>change('section_id',e.target.value)}><option value="">بلا شعبة</option>{options.sections.filter(s=>s.class_id===Number(form.class_id)&&s.status==='active').map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label></div>
 {form.process!=='admission'&&<div className="grid gap-3 sm:grid-cols-2"><label>المدرسة الخارجية<input className={input} required maxLength={200} value={form.external_school} onChange={e=>change('external_school',e.target.value)} /></label><label>مرجع كتاب النقل<input className={input} required maxLength={250} value={form.document_reference} onChange={e=>change('document_reference',e.target.value)} /></label></div>}
 {evidenceFields(form,(k,v)=>change(k,v))}<button className={button} disabled={busy||!schoolId}>إرسال للمراجعة</button></fieldset></form></details>
 <div className="grid min-w-0 gap-4 lg:grid-cols-2"><section className="space-y-2"><h2 className="font-bold">الطلبات</h2>{rows.length===0&&<p className="p-4 text-gray-500">لا توجد طلبات.</p>}{rows.map(a=><button disabled={busy} className={`w-full rounded-xl border p-3 text-right ${selected?.application_key===a.application_key?'border-primary-500 bg-primary-50':'bg-white'}`} key={a.application_key} onClick={()=>void choose(a)}><b className="block">{a.student_name||a.applicant?.full_name}</b><span>{ADMISSION_PROCESSES[a.process]} · {labels[a.status]}</span></button>)}{cursor&&<button className={button} onClick={()=>void load(cursor)}>المزيد</button>}</section>
 {selected&&<section className="min-w-0 space-y-4 rounded-xl border bg-white p-4"><h2 className="font-bold">{selected.student_name||selected.applicant?.full_name} — {labels[selected.status]}</h2>{preview&&<div className={`space-y-2 rounded-lg p-3 ${preview.can_approve?'bg-emerald-50':'bg-amber-50'}`}><b>{preview.can_approve?'مستوفٍ للشروط المسجلة':'يحتاج معالجة قبل الاعتماد'}</b>{[...preview.eligibility.issues,...preview.operational_issues].map((v,i)=><p key={i} className="text-sm">• {v}</p>)}{preview.regulation&&<p className="text-sm">{preview.regulation.title} — إصدار {preview.regulation.version} · <a href={preview.regulation.source_url} target="_blank" rel="noreferrer" className="underline">{preview.regulation.source_reference}</a></p>}</div>}
 {selected.status==='submitted'&&<details><summary>تحديث بيانات المراجعة</summary><div className="mt-3 space-y-3">{evidenceFields(edit,(k,v)=>setEdit(f=>({...f,[k]:v})))}<button className={button} disabled={busy||!reason.trim()} onClick={()=>void action('facts')}>حفظ بيانات المراجعة</button></div></details>}
 {(selected.status==='submitted'||selected.status==='approved')&&<label className="block">سبب الإجراء أو ملاحظة المراجعة<input className={input} maxLength={500} value={reason} onChange={e=>setReason(e.target.value)} /></label>}
 {canDecide&&selected.status==='submitted'&&<div className="space-y-3"><label className="flex gap-2"><input type="checkbox" checked={verified} onChange={e=>setVerified(e.target.checked)} />راجعت المستندات الأصلية والعمر والإعادة والتسريع</label><div className="flex flex-wrap gap-2"><button className={button} disabled={busy||!preview?.can_approve||!verified||!reason.trim()} onClick={()=>void action('approve')}>اعتماد الطلب</button><button className="rounded-lg border px-4 py-2 disabled:opacity-50" disabled={busy||!reason.trim()} onClick={()=>void action('reject')}>رفض بسبب موثق</button><button className="rounded-lg border px-4 py-2 disabled:opacity-50" disabled={busy||!reason.trim()} onClick={()=>void action('cancel')}>إلغاء الطلب</button></div></div>}
 {selected.status==='approved'&&<div className="space-y-3"><label className="flex gap-2"><input type="checkbox" checked={confirm} onChange={e=>setConfirm(e.target.checked)} />أؤكد تنفيذ {ADMISSION_PROCESSES[selected.process]} لهذا الطالب</label><button className={button} disabled={busy||!confirm||!preview?.can_approve} onClick={()=>void action('execute')}>تنفيذ الطلب المعتمد</button>{canDecide&&<div className="flex flex-wrap gap-2"><button className="rounded-lg border p-2 disabled:opacity-50" disabled={busy||!reason.trim()} onClick={()=>void action('reopen')}>إعادة للمراجعة</button><button className="rounded-lg border p-2 disabled:opacity-50" disabled={busy||!reason.trim()} onClick={()=>void action('cancel')}>إلغاء الطلب</button></div>}</div>}
 {selected.status==='executed'&&<p className="rounded-lg bg-emerald-50 p-3">تم التنفيذ وحُفظ السجل التاريخي. يمكنك متابعة ملف الطالب من شؤون الطلاب.</p>}
 <details><summary>سجل الإجراءات</summary>{audit.map((a,i)=><p className="mt-2 break-words text-sm" key={i}>{labels[a.new_status as keyof typeof labels]||a.new_status} — {a.reason||'إنشاء الطلب'} — {new Date(a.created_at*1000).toLocaleString('ar-IQ')}</p>)}</details></section>}</div>
 </div>;
}
