import {useEffect,useRef,useState} from 'react';
import {useAuth} from '../../hooks/useAuth';
import {useTenantSchool} from '../../hooks/useTenantSchool';
import {fetchApi} from '../../lib/api';
import {hasRole,SCHOOL_MANAGEMENT_ROLES} from '../../lib/rbac';
import {ADMISSION_PROCESSES,baghdadDate,type RegulationRecord,type AdmissionRules} from '../../lib/admissionRegulations';
import {useSchoolOptions,workflowInput as input,workflowButton as button} from './useSchoolOptions';
const empty=()=>({academic_year_id:'',class_id:'',process:'admission',title:'',jurisdiction:'',source_reference:'',source_url:'',effective_from:baghdadDate(),effective_to:'',age_reference_date:baghdadDate(),age_rule:'review',min_age_months:'',max_age_months:'',repeat_rule:'review',max_previous_repeats:'',acceleration:'review',documents:''});
export default function RegulationsPage(){
 const {user}=useAuth(),scope=useTenantSchool(),{schoolId}=scope,options=useSchoolOptions(schoolId),canApprove=hasRole(user?.role_key,SCHOOL_MANAGEMENT_ROLES);
 const [rows,setRows]=useState<RegulationRecord[]>([]),[form,setForm]=useState(empty),[selected,setSelected]=useState<RegulationRecord|null>(null),[verified,setVerified]=useState(false),[reason,setReason]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false),[audit,setAudit]=useState<Array<{action:string;reason:string|null;created_at:number}>>([]);
 const epoch=useRef(0),selectionEpoch=useRef(0),key=useRef('');
 async function load(){if(!schoolId)return;const token=epoch.current;const r=await fetchApi<RegulationRecord[]>(`/api/regulations?school_id=${schoolId}`);if(token!==epoch.current)return;if(r.error)setError(r.error);else setRows(r.data||[]);}
 useEffect(()=>{epoch.current++;selectionEpoch.current++;setRows([]);setForm(empty());setSelected(null);setAudit([]);setVerified(false);setReason('');setError('');setBusy(false);key.current='';void load();return()=>{epoch.current++;};},[schoolId]);
 function change(k:keyof ReturnType<typeof empty>,v:string){setForm(f=>({...f,[k]:v}));key.current='';}
 async function choose(r:RegulationRecord){setSelected(r);setVerified(false);setReason('');setAudit([]);const token=epoch.current,selection=++selectionEpoch.current;const res=await fetchApi<Array<{action:string;reason:string|null;created_at:number}>>(`/api/regulations/${r.regulation_key}/audit?school_id=${schoolId}`);if(token===epoch.current&&selection===selectionEpoch.current&&!res.error)setAudit(res.data||[]);}
 function copy(r:RegulationRecord){setForm({academic_year_id:String(r.academic_year_id),class_id:String(r.class_id),process:r.process,title:r.title,jurisdiction:r.jurisdiction,source_reference:r.source_reference,source_url:r.source_url,effective_from:r.effective_from,effective_to:r.effective_to,age_reference_date:r.rules.age_reference_date,age_rule:r.rules.age_rule,min_age_months:r.rules.min_age_months==null?'':String(r.rules.min_age_months),max_age_months:r.rules.max_age_months==null?'':String(r.rules.max_age_months),repeat_rule:r.rules.repeat_rule,max_previous_repeats:r.rules.max_previous_repeats==null?'':String(r.rules.max_previous_repeats),acceleration:r.rules.acceleration,documents:r.rules.required_documents.join('\n')});key.current='';window.scrollTo({top:0,behavior:'smooth'});}
 async function save(e:React.FormEvent){e.preventDefault();if(!schoolId||busy)return;const token=epoch.current;setBusy(true);setError('');key.current ||= crypto.randomUUID();const n=(v:string)=>v.trim()===''?null:Number(v);
 const rules:AdmissionRules={age_reference_date:form.age_reference_date,age_rule:form.age_rule as AdmissionRules['age_rule'],min_age_months:n(form.min_age_months),max_age_months:n(form.max_age_months),repeat_rule:form.repeat_rule as AdmissionRules['repeat_rule'],max_previous_repeats:n(form.max_previous_repeats),acceleration:form.acceleration as AdmissionRules['acceleration'],required_documents:form.documents.split('\n').map(s=>s.trim()).filter(Boolean)};
 const r=await fetchApi<RegulationRecord>('/api/regulations',{method:'POST',body:JSON.stringify({school_id:schoolId,regulation_key:key.current,academic_year_id:Number(form.academic_year_id),class_id:Number(form.class_id),process:form.process,title:form.title,jurisdiction:form.jurisdiction,source_reference:form.source_reference,source_url:form.source_url,effective_from:form.effective_from,effective_to:form.effective_to,rules})});if(token!==epoch.current)return;setBusy(false);if(r.error)setError(r.error);else{key.current='';await load();if(r.data)void choose(r.data);}}
 async function approve(){if(!selected||!verified||busy)return;const token=epoch.current;setBusy(true);setError('');const r=await fetchApi<RegulationRecord>(`/api/regulations/${selected.regulation_key}/approve`,{method:'POST',body:JSON.stringify({school_id:schoolId,revision:selected.revision,confirm_source_verified:verified,reason})});if(token!==epoch.current)return;setBusy(false);if(r.error)setError(r.error);else{await load();if(r.data)void choose(r.data);}}
 async function retire(){if(!selected||busy||!reason.trim())return;const token=epoch.current;setBusy(true);setError('');const r=await fetchApi<RegulationRecord>(`/api/regulations/${selected.regulation_key}/retire`,{method:'POST',body:JSON.stringify({school_id:schoolId,revision:selected.revision,reason})});if(token!==epoch.current)return;setBusy(false);if(r.error)setError(r.error);else{await load();if(r.data)void choose(r.data);}}
 const field=(label:string,k:keyof ReturnType<typeof empty>,type='text',required=true)=><label className="block">{label}<input className={input} type={type} required={required} value={form[k]} onChange={e=>change(k,e.target.value)} /></label>;
 return <div dir="rtl" className="space-y-5 p-4 sm:p-6"><h1 className="text-2xl font-bold">لوائح القبول والنقل</h1><p className="text-sm text-gray-600">احفظ كل لائحة مع مصدرها وجهة إصدارها. الاعتماد يحفظ نسخة ثابتة، والتصحيح يكون بإصدار جديد.</p>
 {scope.isSystemAdmin&&<label>المدرسة<select className={input} value={schoolId||''} onChange={e=>scope.selectSchool(e.target.value?Number(e.target.value):null)}><option value="">اختر المدرسة</option>{scope.schools.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label>}
 {(error||options.error)&&<p role="alert" className="rounded-lg bg-red-50 p-3 text-red-700">{error||options.error}</p>}
 <form onSubmit={save} className="space-y-4 rounded-xl border bg-white p-4"><h2 className="font-bold">إصدار لائحة جديد</h2><fieldset disabled={busy} className="space-y-4"><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">
 <label>السنة<select className={input} required value={form.academic_year_id} onChange={e=>change('academic_year_id',e.target.value)}><option value="">اختر السنة</option>{options.years.map(y=><option key={y.id} value={y.id}>{y.name}</option>)}</select></label><label>الصف<select className={input} required value={form.class_id} onChange={e=>change('class_id',e.target.value)}><option value="">اختر الصف</option>{options.classes.filter(c=>c.status==='active').map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label>نوع العملية<select className={input} value={form.process} onChange={e=>change('process',e.target.value)}>{Object.entries(ADMISSION_PROCESSES).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label>
 {field('عنوان اللائحة','title')}{field('الجهة والمنطقة التعليمية','jurisdiction')}{field('رقم الكتاب وتاريخه','source_reference')}{field('رابط المصدر الرسمي','source_url','url')}{field('بداية السريان','effective_from','date')}{field('نهاية السريان','effective_to','date')}
 </div><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3"><label>قاعدة العمر<select className={input} value={form.age_rule} onChange={e=>change('age_rule',e.target.value)}><option value="review">تحتاج مراجعة</option><option value="bounded">حدود موثقة</option><option value="not_applicable">لا تنطبق وفق المصدر</option></select></label>{field('تاريخ احتساب العمر','age_reference_date','date')}{form.age_rule==='bounded'&&<>{field('أقل عمر بالأشهر','min_age_months','number',false)}{field('أعلى عمر بالأشهر','max_age_months','number',false)}</>}
 <label>قاعدة الإعادة<select className={input} value={form.repeat_rule} onChange={e=>change('repeat_rule',e.target.value)}><option value="review">تحتاج مراجعة</option><option value="bounded">حد موثق</option><option value="not_applicable">لا تنطبق وفق المصدر</option></select></label>{form.repeat_rule==='bounded'&&field('أقصى عدد سنوات إعادة','max_previous_repeats','number')}
 <label>التسريع<select className={input} value={form.acceleration} onChange={e=>change('acceleration',e.target.value)}><option value="review">يحتاج مراجعة</option><option value="allowed">مسموح وفق المصدر</option><option value="prohibited">غير مسموح وفق المصدر</option></select></label></div>
 <label className="block">المستندات المطلوبة — سطر لكل مستند<textarea className={input} rows={3} value={form.documents} onChange={e=>change('documents',e.target.value)} /></label><button className={button} disabled={busy||!schoolId}>حفظ مسودة الإصدار</button></fieldset></form>
 <div className="grid gap-4 lg:grid-cols-2"><section className="space-y-2"><h2 className="font-bold">الإصدارات</h2>{rows.length===0&&<p className="text-gray-500">لا توجد لوائح محفوظة.</p>}{rows.map(r=><button disabled={busy} className={`w-full rounded-lg border p-3 text-right ${selected?.regulation_key===r.regulation_key?'border-primary-500 bg-primary-50':'bg-white'}`} key={r.regulation_key} onClick={()=>void choose(r)}><b className="block">{r.title} — إصدار {r.version}</b><span>{ADMISSION_PROCESSES[r.process]} · {{draft:'مسودة',approved:'معتمدة',retired:'موقوفة'}[r.status]}</span></button>)}</section>
 {selected&&<section className="min-w-0 space-y-3 rounded-xl border bg-white p-4"><h2 className="font-bold">{selected.title}</h2><p>{selected.jurisdiction} · {selected.source_reference}</p><a className="break-all text-primary-700 underline" href={selected.source_url} target="_blank" rel="noreferrer">فتح المصدر</a><p className="text-sm">السريان: {selected.effective_from} — {selected.effective_to}</p><p className="text-sm">المستندات: {selected.rules.required_documents.join('، ')||'لا مستندات إضافية مدرجة'}</p><button className="rounded-lg border px-3 py-2" onClick={()=>copy(selected)}>إعداد إصدار جديد من هذه اللائحة</button>
 {canApprove&&selected.status==='draft'&&<div className="space-y-3 border-t pt-3"><label className="flex gap-2"><input type="checkbox" checked={verified} onChange={e=>setVerified(e.target.checked)} />راجعت المصدر الرسمي ونطاق تطبيق القواعد</label><label className="block">ملاحظة الاعتماد<input className={input} value={reason} maxLength={500} onChange={e=>setReason(e.target.value)} /></label><button className={button} disabled={busy||!verified||!reason.trim()} onClick={()=>void approve()}>اعتماد هذا الإصدار</button></div>}
 {canApprove&&selected.status==='approved'&&<div className="space-y-3 border-t pt-3"><label className="block">سبب إيقاف اللائحة<input className={input} value={reason} maxLength={500} onChange={e=>setReason(e.target.value)} /></label><button className="rounded-lg border border-red-300 px-4 py-2 text-red-700 disabled:opacity-50" disabled={busy||!reason.trim()} onClick={()=>void retire()}>إيقاف اعتماد اللائحة</button></div>}
 <details><summary>سجل الإجراءات</summary>{audit.map((a,i)=><p className="mt-2 text-sm" key={i}>{{draft:'مسودة',approved:'اعتماد',retired:'إيقاف'}[a.action]||a.action} — {a.reason||'إنشاء'} — {new Date(a.created_at*1000).toLocaleString('ar-IQ')}</p>)}</details></section>}</div>
 </div>;
}
